// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniPM.Api.Data;

#nullable disable

namespace UniPM.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260711123548_AddMaintenanceSearchDocumentEmbeddings")]
    partial class AddMaintenanceSearchDocumentEmbeddings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UniPM.Api.Models.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssetCategory")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("AssetCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Building")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Department")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("DescriptionEmbedding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("QrCodeValue")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("AssetCode")
                        .IsUnique();

                    b.HasIndex("QrCodeValue")
                        .IsUnique()
                        .HasFilter("[QrCodeValue] IS NOT NULL");

                    b.HasIndex("AssetCategory", "Status");

                    b.ToTable("Assets", null, t =>
                        {
                            t.HasCheckConstraint("CK_Assets_AssetCategory_Allowed", "[AssetCategory] IN ('fire-extinguisher', 'fire-alarm', 'emergency-light', 'water-drinking-station')");

                            t.HasCheckConstraint("CK_Assets_Status_Allowed", "[Status] IN ('Active', 'Inactive', 'Retired')");
                        });
                });

            modelBuilder.Entity("UniPM.Api.Models.InspectionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionsRecommendations")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DateInspected")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("InspectorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsOperational")
                        .HasColumnType("bit");

                    b.Property<string>("Remarks")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("RemarksEmbedding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("InspectionRecords");
                });

            modelBuilder.Entity("UniPM.Api.Models.MaintenanceSearchDocument", b =>
                {
                    b.Property<Guid>("InspectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssetCategory")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("AssetCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AssetUpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Building")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("DateInspected")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Department")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsOperational")
                        .HasColumnType("bit");

                    b.Property<string>("IssueKeysJson")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("LexiconVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Location")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ProjectionVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SearchText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("SourceCreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("SourceUpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("InspectionId");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("AssetCategory", "DateInspected");

                    b.HasIndex("AssetId", "DateInspected");

                    b.HasIndex("IsOperational", "DateInspected");

                    b.ToTable("MaintenanceSearchDocuments");
                });

            modelBuilder.Entity("UniPM.Api.Models.MaintenanceSearchDocumentEmbedding", b =>
                {
                    b.Property<Guid>("InspectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Dimensions")
                        .HasColumnType("int");

                    b.Property<string>("EmbeddingProfile")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModelKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SourceHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("VectorJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InspectionId");

                    b.HasIndex("EmbeddingProfile", "SourceHash");

                    b.ToTable("MaintenanceSearchDocumentEmbeddings", null, t =>
                        {
                            t.HasCheckConstraint("CK_MaintenanceSearchDocumentEmbeddings_Dimensions", "[Dimensions] BETWEEN 1 AND 4096");

                            t.HasCheckConstraint("CK_MaintenanceSearchDocumentEmbeddings_VectorJson", "ISJSON([VectorJson]) = 1");
                        });
                });

            modelBuilder.Entity("UniPM.Api.Models.PreventiveMaintenanceSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AcademicYear")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignedToUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PeriodType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Quarter")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<DateTimeOffset>("ScheduleDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Semester")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Status", "ScheduleDate");

                    b.HasIndex("AssetId", "Status", "ScheduleDate");

                    b.ToTable("PreventiveMaintenanceSchedules", null, t =>
                        {
                            t.HasCheckConstraint("CK_Schedules_AcademicYear_Format", "[AcademicYear] IS NULL OR [AcademicYear] LIKE '[0-9][0-9][0-9][0-9]-[0-9][0-9][0-9][0-9]'");

                            t.HasCheckConstraint("CK_Schedules_PeriodType_Allowed", "[PeriodType] IN ('Quarter', 'Semester', 'Annual', 'Custom')");

                            t.HasCheckConstraint("CK_Schedules_Quarter_Allowed", "[Quarter] IS NULL OR [Quarter] IN ('Q1', 'Q2', 'Q3', 'Q4')");

                            t.HasCheckConstraint("CK_Schedules_Semester_Allowed", "[Semester] IS NULL OR [Semester] IN ('First', 'Second', 'Summer')");

                            t.HasCheckConstraint("CK_Schedules_Status_Allowed", "[Status] IN ('Due', 'Ongoing', 'Completed', 'Overdue', 'Cancelled')");
                        });
                });

            modelBuilder.Entity("UniPM.Api.Models.InspectionRecord", b =>
                {
                    b.HasOne("UniPM.Api.Models.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("UniPM.Api.Models.PreventiveMaintenanceSchedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("UniPM.Api.Models.MaintenanceSearchDocument", b =>
                {
                    b.HasOne("UniPM.Api.Models.InspectionRecord", "Inspection")
                        .WithOne()
                        .HasForeignKey("UniPM.Api.Models.MaintenanceSearchDocument", "InspectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inspection");
                });

            modelBuilder.Entity("UniPM.Api.Models.MaintenanceSearchDocumentEmbedding", b =>
                {
                    b.HasOne("UniPM.Api.Models.MaintenanceSearchDocument", "SearchDocument")
                        .WithOne("Embedding")
                        .HasForeignKey("UniPM.Api.Models.MaintenanceSearchDocumentEmbedding", "InspectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SearchDocument");
                });

            modelBuilder.Entity("UniPM.Api.Models.PreventiveMaintenanceSchedule", b =>
                {
                    b.HasOne("UniPM.Api.Models.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("UniPM.Api.Models.MaintenanceSearchDocument", b =>
                {
                    b.Navigation("Embedding");
                });
#pragma warning restore 612, 618
        }
    }
}
