/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AppAssetsIndexRouteImport } from './routes/app/assets/index'
import { Route as AppAssetsAssetIdRouteImport } from './routes/app/assets/$assetId'
import { Route as AppAssetsNewRouteImport } from './routes/app/assets/new'
import { Route as AppInspectionsIndexRouteImport } from './routes/app/inspections/index'
import { Route as AppInspectionsInspectionIdRouteImport } from './routes/app/inspections/$inspectionId'
import { Route as AppSchedulesIndexRouteImport } from './routes/app/schedules/index'
import { Route as AppSchedulesScheduleIdRouteImport } from './routes/app/schedules/$scheduleId'
import { Route as AppSchedulesNewRouteImport } from './routes/app/schedules/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAssetsIndexRoute = AppAssetsIndexRouteImport.update({
  id: '/assets/',
  path: '/assets/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAssetsAssetIdRoute = AppAssetsAssetIdRouteImport.update({
  id: '/assets/$assetId',
  path: '/assets/$assetId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAssetsNewRoute = AppAssetsNewRouteImport.update({
  id: '/assets/new',
  path: '/assets/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInspectionsIndexRoute = AppInspectionsIndexRouteImport.update({
  id: '/inspections/',
  path: '/inspections/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInspectionsInspectionIdRoute =
  AppInspectionsInspectionIdRouteImport.update({
    id: '/inspections/$inspectionId',
    path: '/inspections/$inspectionId',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppSchedulesIndexRoute = AppSchedulesIndexRouteImport.update({
  id: '/schedules/',
  path: '/schedules/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSchedulesScheduleIdRoute = AppSchedulesScheduleIdRouteImport.update({
  id: '/schedules/$scheduleId',
  path: '/schedules/$scheduleId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSchedulesNewRoute = AppSchedulesNewRouteImport.update({
  id: '/schedules/new',
  path: '/schedules/new',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/': typeof AppIndexRoute
  '/app/assets/$assetId': typeof AppAssetsAssetIdRoute
  '/app/assets/new': typeof AppAssetsNewRoute
  '/app/inspections/$inspectionId': typeof AppInspectionsInspectionIdRoute
  '/app/schedules/$scheduleId': typeof AppSchedulesScheduleIdRoute
  '/app/schedules/new': typeof AppSchedulesNewRoute
  '/app/assets/': typeof AppAssetsIndexRoute
  '/app/inspections/': typeof AppInspectionsIndexRoute
  '/app/schedules/': typeof AppSchedulesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app': typeof AppIndexRoute
  '/app/assets/$assetId': typeof AppAssetsAssetIdRoute
  '/app/assets/new': typeof AppAssetsNewRoute
  '/app/inspections/$inspectionId': typeof AppInspectionsInspectionIdRoute
  '/app/schedules/$scheduleId': typeof AppSchedulesScheduleIdRoute
  '/app/schedules/new': typeof AppSchedulesNewRoute
  '/app/assets': typeof AppAssetsIndexRoute
  '/app/inspections': typeof AppInspectionsIndexRoute
  '/app/schedules': typeof AppSchedulesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/': typeof AppIndexRoute
  '/app/assets/$assetId': typeof AppAssetsAssetIdRoute
  '/app/assets/new': typeof AppAssetsNewRoute
  '/app/inspections/$inspectionId': typeof AppInspectionsInspectionIdRoute
  '/app/schedules/$scheduleId': typeof AppSchedulesScheduleIdRoute
  '/app/schedules/new': typeof AppSchedulesNewRoute
  '/app/assets/': typeof AppAssetsIndexRoute
  '/app/inspections/': typeof AppInspectionsIndexRoute
  '/app/schedules/': typeof AppSchedulesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/dashboard'
    | '/app/'
    | '/app/assets/$assetId'
    | '/app/assets/new'
    | '/app/inspections/$inspectionId'
    | '/app/schedules/$scheduleId'
    | '/app/schedules/new'
    | '/app/assets/'
    | '/app/inspections/'
    | '/app/schedules/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/dashboard'
    | '/app'
    | '/app/assets/$assetId'
    | '/app/assets/new'
    | '/app/inspections/$inspectionId'
    | '/app/schedules/$scheduleId'
    | '/app/schedules/new'
    | '/app/assets'
    | '/app/inspections'
    | '/app/schedules'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/dashboard'
    | '/app/'
    | '/app/assets/$assetId'
    | '/app/assets/new'
    | '/app/inspections/$inspectionId'
    | '/app/schedules/$scheduleId'
    | '/app/schedules/new'
    | '/app/assets/'
    | '/app/inspections/'
    | '/app/schedules/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/assets/': {
      id: '/app/assets/'
      path: '/assets'
      fullPath: '/app/assets/'
      preLoaderRoute: typeof AppAssetsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/assets/$assetId': {
      id: '/app/assets/$assetId'
      path: '/assets/$assetId'
      fullPath: '/app/assets/$assetId'
      preLoaderRoute: typeof AppAssetsAssetIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/assets/new': {
      id: '/app/assets/new'
      path: '/assets/new'
      fullPath: '/app/assets/new'
      preLoaderRoute: typeof AppAssetsNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/inspections/': {
      id: '/app/inspections/'
      path: '/inspections'
      fullPath: '/app/inspections/'
      preLoaderRoute: typeof AppInspectionsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/inspections/$inspectionId': {
      id: '/app/inspections/$inspectionId'
      path: '/inspections/$inspectionId'
      fullPath: '/app/inspections/$inspectionId'
      preLoaderRoute: typeof AppInspectionsInspectionIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/schedules/': {
      id: '/app/schedules/'
      path: '/schedules'
      fullPath: '/app/schedules/'
      preLoaderRoute: typeof AppSchedulesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/schedules/$scheduleId': {
      id: '/app/schedules/$scheduleId'
      path: '/schedules/$scheduleId'
      fullPath: '/app/schedules/$scheduleId'
      preLoaderRoute: typeof AppSchedulesScheduleIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/schedules/new': {
      id: '/app/schedules/new'
      path: '/schedules/new'
      fullPath: '/app/schedules/new'
      preLoaderRoute: typeof AppSchedulesNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAssetsAssetIdRoute: typeof AppAssetsAssetIdRoute
  AppAssetsNewRoute: typeof AppAssetsNewRoute
  AppInspectionsInspectionIdRoute: typeof AppInspectionsInspectionIdRoute
  AppSchedulesScheduleIdRoute: typeof AppSchedulesScheduleIdRoute
  AppSchedulesNewRoute: typeof AppSchedulesNewRoute
  AppAssetsIndexRoute: typeof AppAssetsIndexRoute
  AppInspectionsIndexRoute: typeof AppInspectionsIndexRoute
  AppSchedulesIndexRoute: typeof AppSchedulesIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppIndexRoute: AppIndexRoute,
  AppAssetsAssetIdRoute: AppAssetsAssetIdRoute,
  AppAssetsNewRoute: AppAssetsNewRoute,
  AppInspectionsInspectionIdRoute: AppInspectionsInspectionIdRoute,
  AppSchedulesScheduleIdRoute: AppSchedulesScheduleIdRoute,
  AppSchedulesNewRoute: AppSchedulesNewRoute,
  AppAssetsIndexRoute: AppAssetsIndexRoute,
  AppInspectionsIndexRoute: AppInspectionsIndexRoute,
  AppSchedulesIndexRoute: AppSchedulesIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
